name: 🐞 Compatibility report
description: Create a report on missing features from Bootstrap v5 or BootstrapVue v2
labels: [compatibility enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this compatibility report!
  - type: dropdown
    id: feature-type
    attributes:
      label: Missing feature is from
      description: Please include a detailed description of the feature, and a web link to the Bootstrap-vue docs or to the most current version of the Bootstrap docs.
      options:
        - bootstrap-vue
        - Bootstrap v5
    validations:
      required: true
  - type: textarea
    id: feature-description
    attributes:
      label: Describe the missing feature
      description: A clear and concise description of what is missing. If you intend to submit a PR for this issue, tell us in the description. Thanks!
      placeholder: Feature description
    validations:
      required: true
  - type: input
    id: docs
    attributes:
      label: Docs
      description: Please provide a link to the Bootstrap-vue docs or the most current version of the Bootstrap docs for this feature.
      placeholder: link
    validations:
      required: true
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Have tested with the latest version. This is still alpha version and sometime things change rapidly.
          required: true
        - label: Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
          required: true
        - label: Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
          required: true
        - label: Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
          required: true
        - label: Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
          required: true
        - label: The provided link is to the documentation of the missing feature.
          required: true